[package]
name = "epoxy"
version = "0.0.1"
authors = ["Maxwell Koo <mjkoo90@gmail.com>"]
build = "build.rs"

[build-dependencies]
gl_generator = "^0.1"
khronos_api = "^0"

[dependencies]
libc = "^0.1"
gl_common = "^0.1"
